### ISSUE TITLE
Feature: List active window for each monitor

### ISSUE THREAD

**Issue by Vinschers** [FieldofClay/hyprland-activewindow#1]
Thank you for this amazing small program. It was just what I needed!

I was wondering if you could add an option like [hyprland-workspaces](https://github.com/FieldofClay/hyprland-workspaces) (`hyprland-workspaces _`) so that each monitor prints its active window.

If you could also print this information in json, it would be possible to define a single widget in eww with a parameter. Something like the following
```
(deflisten windows "hyprland-activewindow _ --json")

(defwidget window [monitor]
  (box
    (label :text "${windows['${monitor}']}")
  )
)
```
I think this would greatly simplify the eww configuration for multi-monitor setups.

**Comment by FieldofClay** [comment]
I've implemented this under the wildcard branch for testing. Let me know how it goes and I'll merge it into the main branch.

I've forgone the --json flag, as there isn't really any other usable way of outputting all monitors. It uses json automatically when using "_" mode.

**Comment by Vinschers** [comment]
I noticed that the title does not update to an empty string if I close the last window of a workspace. Is this expected behavior?
Other than that, it seems to be working just fine!

**Comment by FieldofClay** [comment]
Thanks for your feedback.

> I noticed that the title does not update to an empty string if I close the last window of a workspace. Is this expected behavior?

That is not expected behaviour and looks like a bug. I've included in a fix with the all monitor support (which I'll call advanced mode).

I'll merge and push out a new release shortly.

**Comment by Vinschers** [comment]
Hey, sorry to reopen this issue, but I think there is some problem with the `proc-macro2` package. I don't really know rust, but I could only compile the code using version `1.0.60` in the Cargo.lock file.
Other than that, it seems that the nightly rust release is required as well. Could you update the PKGBUILD in the AUR to address this?

**Comment by FieldofClay** [comment]
The Cargo.lock file is auto generated by cargo. It shouldn't be edited.

If you're having issues compiling, I would suggest blowing away your local copy and cloning the repo down again. You could also try a `cargo update` if you're still having issues.
