### ISSUE TITLE
Advanced mode not clearing title when closing last window

### ISSUE THREAD

**Issue by FieldofClay** [FieldofClay/hyprland-activewindow#13]
When closing the last window on a workspace and using the advanced mode "_", the last window title remains instead of clearing.

Regular mode appears unaffected.

**Comment by kiike** [comment]
Hi @FieldofClay! First, I'd like to thank you for the activewindow and workspaces tools, as they are very useful for my EWW bar! I encountered this issue when I started using the advanced mode to build the widgets, and I don't understand the logic you are trying to use in `print_all`. It looks to me the condition you want to use to get the clients will never be satisfied, as they are no clients to match against `workspace.last_window`. I edited `print_all` to fill in clients, but skip the error if the workspace has no clients.

**Comment by FieldofClay** [comment]
Yeah, definitely overlooked this when I refactored a bunch of the code. Should be good now.
