### ISSUE TITLE
`Cargo.lock` is out of date

### ISSUE THREAD

**Issue by kiike** [FieldofClay/hyprland-activewindow#20]
Hi @FieldofClay! Thanks for working on the Hyprland 0.40 fixes. Just a heads up, `Cargo.lock` is out of date. I imagine the version of `hyprland-activewindow` was not bumped from beta to stable, so we're hitting a `hyprland-activewindow> error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this` error when building the package.

**Comment by FieldofClay** [comment]
Thanks for this, was being lazy and it didn't cause issues when building through the AUR. Will ensure I keep it up to date in the future for NixOS.

**Comment by kiike** [comment]
That's alright! Thank you for being so responsive!
