### ISSUE TITLE
Request: Update the readme as a lot of examples for some reason don't work anymore

### ISSUE THREAD

**Issue by webwalkerkarma** [FieldofClay/hyprland-activewindow#5]
**Problem 1:**
This [part of readme](https://github.com/FieldofClay/hyprland-activewindow#advanced-mode) no longer works (at least on my machine), title name is always empty
> 
> This allows simplified Eww config similar to this:
> 
> ```
> (deflisten windows "hyprland-activewindow _")
> 
> (defwidget window [monitor]
>   (box
>     (label :text "${windows['${monitor}'].title}")
>   )
> )
> ```
**Solution:**
I couldn't figure out is it a eww bug or how eww now manages JSON object properties, the documentation is not very clear in that regard. Though I got it working with `jq` and `replace` :
```
(defwindow bar0
  ...
  (box :class "bar"
    ...
    (window_w :monitor "HDMI-A-1")
    ...
  )
)

(defwindow bar1
  ...
  (box :class "bar"
    ...
    (window_w :monitor "DP-1")
    ...
  )
)

(deflisten windows "hyprland-activewindow _")

(defwidget window_w [monitor]
  (box
    :class "window_w"
    (label
      :limit-width 40
      :text "${replace(jq('${windows}', '.[] | select(.name == "${monitor}") | .title'),"\(^\"\|\"$\)", "")}"
    )
  )
)
```

**Problem 2:**
This [part of readme](https://github.com/FieldofClay/hyprland-activewindow#basic-mode) doesn't work as well because of `'hyprctl monitors -j | jq -r \".[0].name\'` which for some reason doesn't return a display anymore.
> It can be used as a title widget in Eww with config similar to below.
> 
> ```
> (deflisten window0 "hyprland-activewindow `hyprctl monitors -j | jq -r \".[0].name\"`")
> (defwidget title0 []
>     (label :text "${window0}"))
> 
> (deflisten window1 "hyprland-activewindow `hyprctl monitors -j | jq -r \".[1].name\"`")
> (defwidget title1 []
>     (label :text "${window1}"))
> ```

**Solution:** 
To avoid updating it in the future and not be dependent on hyprctl stuff probably worth to refer the display directly without polling: 
 ```
 (deflisten window0 "hyprland-activewindow DP-1")
 (defwidget title0 []
     (label :text "${window0}"))
 
 (deflisten window1 "hyprland-activewindow DP-2")
 (defwidget title1 []
     (label :text "${window1}"))
 ```

**Comment by FieldofClay** [comment]
What shell are you using? What is the output of `hyprland-activewindow _` when you switch between a number of active windows? Can you run `hyprctl monitors -j | jq -r ".[0].name"` in your terminal and report the output?

I agree that the second example should be simplified, so will update that, but the command `hyprctl monitors -j | jq -r ".[0].name"` still works fine for me. The first example is the same config that I'm still using, with some cosmetic changes (setting class, limiting width), so I'd be keen to troubleshoot further to figure out what is different.

**Comment by webwalkerkarma** [comment]
I was testing old  `hyprctl monitors -j | jq -r \".[0].name\"` in Bash and Fish. In both it returns `.[0].name` instead of display. 
`hyprctl monitors -j | jq -r ".[0].name"` works in both Bash, Fish and also appears to work in zsh.

> What is the output of `hyprland-activewindow _` when you switch between a number of active windows

Mainly using fish, but tested in bash and zsh output is not different there inside of foot/alacritty.
```
[{"name":"DP-1","title":"GitHub — Mozilla Firefox"},{"name":"DP-3","title":"~"},{"name":"HDMI-A-1","title":""}]
[{"name":"DP-1","title":"GitHub — Mozilla Firefox"},{"name":"DP-3","title":"hyprland-activewindo ~"},{"name":"HDMI-A-1","title":""}]
[{"name":"DP-1","title":"GitHub — Mozilla Firefox"},{"name":"DP-3","title":"btop ~"},{"name":"HDMI-A-1","title":""}]
[{"name":"DP-1","title":"GitHub — Mozilla Firefox"},{"name":"DP-3","title":"hyprland-activewindo ~"},{"name":"HDMI-A-1","title":""}]

```
Tried using fish in **kgx** terminal.
And fish there have tendency to double-post first line only on launch, so on launch it outputs following part instantly:
```
[{"name":"DP-1","title":"GitHub — Mozilla Firefox"},{"name":"DP-3","title":"~"},{"name":"HDMI-A-1","title":""}]
[{"name":"DP-1","title":"GitHub — Mozilla Firefox"},{"name":"DP-3","title":"hyprland-activewindo ~"},{"name":"HDMI-A-1","title":""}]
```

**Comment by FieldofClay** [comment]
Looks like you've got an escaping issue going on here. `hyprctl monitors -j | jq -r \".[0].name\"` was used in the documentation because it was already in a pair of quotes, hence the need to escape them within the eww config. When running the command in the terminal you'll need to remove the backslash escapes. 

It looks like the app is outputting the correct info now. If you're still having issues, let me know what the values of the variables within eww are (`eww state`).

**Comment by FieldofClay** [comment]
no response > 1 month, closing.
