### ISSUE TITLE
Is it possible to just get the title of the window itself?

### ISSUE THREAD

**Issue by B21q** [FieldofClay/hyprland-activewindow#6]
Is it possible to just get the title of the window itself? For example, only firefox, only alacritty, only neovim. At the moment it captures the full title of the window

**Comment by FieldofClay** [comment]
I may be possible. Have a look at the output of `hyprctl clients -j`, specifically at initialTitle and class. Do they look more like what you're after? Currently the app is pulling from title, but wouldn't be too difficult to include those extra fields in the advanced version of the app.

**Comment by B21q** [comment]
Yes, I'll read the code one of these days haha, I'm making a Rice in eww
and I think it would look better just showing the title of the app.

Em seg., 29 de jan. de 2024 22:02, FieldofClay ***@***.***>
escreveu:

**Comment by FieldofClay** [comment]
The initial title of a window is now output in advanced mode, alongside the current title.
